// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class Group
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int? GuestNumber { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int? Quantity { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? StaffId { get; set; }

    public Guid? WelcomeId { get; set; }

    public Guid? EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Guest> Guests { get; set; } = new List<Guest>();

    public virtual Staff Staff { get; set; }

    public virtual WelcomeTemplate Welcome { get; set; }
}