// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class GuestImage
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Type { get; set; }

    public string Path { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? GuestId { get; set; }

    public virtual Guest Guest { get; set; }
}