// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class Guest
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public DateTime? CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? EventId { get; set; }

    public Guid? GroupId { get; set; }

    public Guid? PersonId { get; set; }

    public virtual Event Event { get; set; }

    public virtual Group Group { get; set; }

    public virtual ICollection<GuestImage> GuestImages { get; set; } = new List<GuestImage>();

    public virtual Person Person { get; set; }
}