// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class Organization
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Status { get; set; }

    public Guid? OrganizationGroupId { get; set; }

    public virtual OrganizationGroup OrganizationGroup { get; set; }

    public virtual ICollection<Person> People { get; set; } = new List<Person>();
}