// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class Person
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Position { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Image { get; set; }

    public Guid? OrganizationId { get; set; }

    public virtual ICollection<Guest> Guests { get; set; } = new List<Guest>();

    public virtual Organization Organization { get; set; }
}