// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class Staff
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public Guid? EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();
}