// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FaceWelcome.Repository.Models;

public partial class WelcomeTemplate
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Content { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();
}